<a href="https://colab.research.google.com/github/vonvon56/cl_practice/blob/main/%EC%96%B8%EC%BB%B4_np_pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

Numpy

In [1]:
import numpy as np
import re

In [ ]:
a = [[1,2,3],[4,5,6]]
#np 형식으로 만들기
a_np = np.array(a)

print(a)
print(a_np)
print(a_np.sum())

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
21


In [10]:
#full
a = np.full(6,5)
print(a)
a = np.full([3,4],1)
print(a)
a = np.random.random([3,4])
print(a)

[5 5 5 5 5 5]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.15735485 0.07084002 0.65720764 0.0824412 ]
 [0.88640442 0.27948718 0.64593541 0.82456908]
 [0.12764545 0.03635536 0.85347161 0.44423054]]


In [40]:
#배열 생성하는 다른 방법 - arange
np_10 = np.arange(2,10)
print(np_10)
#np.zeros(), np.ones()
np_zero = np.zeros((3,4))
print(np_zero)
#n행m열로 변환하기: .reshape()
reshaped = np_10.reshape(2,4)
print(reshaped)

[2 3 4 5 6 7 8 9]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2 3 4 5]
 [6 7 8 9]]


In [13]:
#배열에서 특정 원소의 인덱스 찾기: where
spot = str(np.where(reshaped == 7))
print(spot)
x,y = map(int,re.findall(r'(?<=\[)[0-9]+(?=\])', spot))
print(x,y)
print(reshaped[x,y:])

(array([1]), array([1]))
1 1
[7 8 9]


In [15]:
#배열 연산
arr = np.arange(15).reshape(3,5) + 1
print(arr)
print(np.max(arr, axis=1)) #1: 각 행에서 최대
print(np.max(arr, axis=0)) #0: 각 열에서 최대

print(np.mean(arr, axis=0))

print(np.mean(arr, axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 5 10 15]
[11 12 13 14 15]
[ 6.  7.  8.  9. 10.]
[ 3.  8. 13.]


In [20]:
#조건 주면 T/F 담아서 array로 리턴
arr > 9
print(arr)
#True인 곳 찾기 : np.where()
boolean = arr>9
print(boolean)
haha = np.where(boolean)
haha

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[False False False False False]
 [False False False False  True]
 [ True  True  True  True  True]]


(array([1, 2, 2, 2, 2, 2]), array([4, 0, 1, 2, 3, 4]))

In [30]:
import numpy as np

arr = np.array([[1, 5, 12, 8],
                [9, 3, 7, 10],
                [15, 2, 6, 11]])



# np.where()를 사용하여 True인 위치를 찾습니다.
haha = np.where(arr>9)

# haha를 출력합니다.
print(haha)
arr[haha]

(array([0, 1, 2, 2]), array([2, 3, 0, 3]))


array([12, 10, 15, 11])

In [31]:
#표준편차, 분산
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875


In [ ]:
#중앙값
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값

In [32]:
#평균값
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean()) # 평균값

15.25




---

Pandas

In [35]:
import pandas as pd

In [38]:
!wget https://raw.githubusercontent.com/sanajlee/lingdat/master/students.csv

--2023-09-30 07:57:03--  https://raw.githubusercontent.com/sanajlee/lingdat/master/students.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214 [text/plain]
Saving to: ‘students.csv’

students.csv        100%[===================>]     214  --.-KB/s    in 0s      

2023-09-30 07:57:03 (11.7 MB/s) - ‘students.csv’ saved [214/214]



In [39]:
#열기: pd.read_csv, column도 지정할 수 있음.
columns = ['year','class','name','message']
std = pd.read_csv('students.csv',names=columns)
print(std)

   year  class name                     message
0     1      1  김뽀삐            단발머리 하고 지난 일은 잊고
1     1      9  송초코               나 새롭게 태어날 거예요
2     2      7  이야옹          It's gonna be fine
3     3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자


In [45]:
df = pd.DataFrame(reshaped, columns = ['a','b','c','d'], index=['서울','경기'])
df

a  b  c  d
서울  2  3  4  5
경기  6  7  8  9

In [ ]:
#series: 1열짜리 행렬
a = pd.Series([1,2,3,4,5], index=['first','second','third','fourth','fifth'])
print(a)

d = {'b':1, "a": 0, "c": 10}
d = pd.Series(d)
print(d)

first     1
second    2
third     3
fourth    4
fifth     5
dtype: int64
b     1
a     0
c    10
dtype: int64


In [ ]:
dict1 = {
    "A": 1.0,
    "B" : pd.Timestamp('20230929'),
    "C" : pd.Series(1, index=list(range(3,7)), dtype='float32')  ,
    'D' : [3]*4,
    'E' : pd.Categorical(['test','train','test','train']),
    'F' : 'foo'

}
pd.DataFrame(dict1)

A          B    C  D      E    F
3  1.0 2023-09-29  1.0  3   test  foo
4  1.0 2023-09-29  1.0  3  train  foo
5  1.0 2023-09-29  1.0  3   test  foo
6  1.0 2023-09-29  1.0  3  train  foo

In [ ]:
pd.Series(1, index=list(range(3,7)), dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [ ]:
#파일로부터 데이터 불러와서 DataFrame 생성
!wget https://raw.githubusercontent.com/sanajlee/lingdat/master/students.csv
!wget https://raw.githubusercontent.com/sanajlee/lingdat/master/students.tsv

--2023-09-29 11:09:29--  https://raw.githubusercontent.com/sanajlee/lingdat/master/students.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214 [text/plain]
Saving to: ‘students.csv.1’

students.csv.1      100%[===================>]     214  --.-KB/s    in 0s      

2023-09-29 11:09:29 (11.9 MB/s) - ‘students.csv.1’ saved [214/214]

--2023-09-29 11:09:29--  https://raw.githubusercontent.com/sanajlee/lingdat/master/students.tsv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 214 [text/plain]
Saving to: ‘students.tsv’

students.

In [46]:
####index_col='name'으로 맨 처음 column명 지을 수도 있다.
names = ['grade','class','name','message']
students = pd.read_csv('students.csv', header =None, names=names, index_col='name')
students

grade  class                     message
name                                          
김뽀삐       1      1            단발머리 하고 지난 일은 잊고
송초코       1      9               나 새롭게 태어날 거예요
이야옹       2      7          It's gonna be fine
한재훈       3      5  얘들아 3년 동안 수고했고 나중에 웃으면서 보자

In [ ]:
names = ['grade','class','name','message']
students = pd.read_csv('students.tsv', header =None, names=names, sep='\t')
print(students)
students.loc[3, 'message'] = '''aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'''
#loc: 인덱스 슬라이싱. 1:3이면 1부터 2까지 아니고 3까지.
#iloc: 상대적인 위치로 접근. 이건 진짜 index처럼 다룸. 1:3 -> 2번째부터 3번째

print(students.iloc[1:3])
students

   grade  class name                     message
0      1      1  김뽀삐            단발머리 하고 지난 일은 잊고
1      1      9  송초코               나 새롭게 태어날 거예요
2      2      7  이야옹          It's gonna be fine
3      3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자
   grade  class name             message
1      1      9  송초코       나 새롭게 태어날 거예요
2      2      7  이야옹  It's gonna be fine


grade  class name                                            message
0      1      1  김뽀삐                                   단발머리 하고 지난 일은 잊고
1      1      9  송초코                                      나 새롭게 태어날 거예요
2      2      7  이야옹                                 It's gonna be fine
3      3      5  한재훈  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\naaaa...

In [ ]:
#대표적 통계치 출력: describe()
students.describe()

grade    class
count  4.000000  4.00000
mean   1.750000  5.50000
std    0.957427  3.41565
min    1.000000  1.00000
25%    1.000000  4.00000
50%    1.500000  6.00000
75%    2.250000  7.50000
max    3.000000  9.00000

In [ ]:
#정렬 : axis = 0: 행 기준
students.sort_index(axis=0,  ascending = False)

grade  class name                     message
3      3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자
2      2      7  이야옹          It's gonna be fine
1      1      9  송초코               나 새롭게 태어날 거예요
0      1      1  김뽀삐            단발머리 하고 지난 일은 잊고

In [ ]:
#정렬: axis=1: 열 기준
students.sort_index(axis=1)

class  grade                     message name
0      1      1            단발머리 하고 지난 일은 잊고  김뽀삐
1      9      1               나 새롭게 태어날 거예요  송초코
2      7      2          It's gonna be fine  이야옹
3      5      3  얘들아 3년 동안 수고했고 나중에 웃으면서 보자  한재훈

In [ ]:
#정렬: 데이터 필드 값 기준
students.sort_values(by='message')

grade  class name                     message
2      2      7  이야옹          It's gonna be fine
1      1      9  송초코               나 새롭게 태어날 거예요
0      1      1  김뽀삐            단발머리 하고 지난 일은 잊고
3      3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자

In [ ]:
students[students['grade'] >= 2]

grade  class name                     message
2      2      7  이야옹          It's gonna be fine
3      3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자

In [ ]:
students[students['class'].isin([5,7])]

grade  class name                     message
2      2      7  이야옹          It's gonna be fine
3      3      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자

In [ ]:
print(students.mean())
print(students.mean(1))
students.mean()['class']
students.sum()

grade    1.75
class    5.50
dtype: float64
0    1.0
1    5.0
2    4.5
3    4.0
dtype: float64


<ipython-input-51-2fd23da92ce1>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(students.mean())
<ipython-input-51-2fd23da92ce1>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(students.mean(1))
<ipython-input-51-2fd23da92ce1>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  students.mean()['class']


grade                                                      7
class                                                     22
name                                            김뽀삐송초코이야옹한재훈
message    단발머리 하고 지난 일은 잊고나 새롭게 태어날 거예요It's gonna be fin...
dtype: object

In [ ]:
#groupby: 묶기
students.groupby('grade').mean()

<ipython-input-53-2f4a0fc0f7d8>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  students.groupby('grade').mean()


class
grade       
1        5.0
2        7.0
3        5.0

In [ ]:
#apply() : 여러 cell에 대해 일괄적으로 하나의 함수 적용
def add_1(grade):
    if grade == 3:
        new_grade = 0
    else:
        new_grade = grade + 1
    return new_grade

students['grade'] = students['grade'].apply(add_1)
students

grade  class name                     message
0      2      1  김뽀삐            단발머리 하고 지난 일은 잊고
1      2      9  송초코               나 새롭게 태어날 거예요
2      3      7  이야옹          It's gonna be fine
3      0      5  한재훈  얘들아 3년 동안 수고했고 나중에 웃으면서 보자